sudo: required
services: 
- docker

before_install:
- docker build -t mhkhong/docker-react -f Dockerfile.dev .

script:
- docker run -e CI=true mhkhong/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-east-2-696166494989"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
